#!/usr/bin/env php
<?php
/**
 *  PHP 入口执行
 *  没有控制器的脚本
 * Created by PhpStorm.
 * User: shengsheng
 * Date: 2018/7/19
 * Time: 下午11:41
 */

// __DIR__
$dirPath = realpath(getcwd());

$dir = $dirPath.'/..';

if (!file_exists($dir.'/autoload.php')) {
    $dir = $dirPath.'/../vendor';
}

if (!file_exists($dir.'/autoload.php')) {
    $dir = $dirPath.'/../../..';
}

if (!file_exists($dir.'/autoload.php')) {
    echo 'Autoload not found.';
    exit(1);
}

require $dir.'/autoload.php';
/**
 *  PHP 入口执行
 *  没有控制器的脚本
 * Created by PhpStorm.
 * User: shengsheng
 * Date: 2018/7/19
 * Time: 下午11:41
 */
\phpshow\loader::start();