#!/usr/bin/env php
<?php
// echo "cli\n";
$bin_path = realpath(getcwd());
require $bin_path.'/../autoload.php';
use \phpshow\loader;
/**
 *  PHP 入口执行
 *  没有控制器的脚本
 * Created by PhpStorm.
 * User: shengsheng
 * Date: 2018/7/19
 * Time: 下午11:41
 */
loader::start($argc,$argv);