#!/usr/bin/env php
<?php
/**
 *  PHP 入口执行
 *  没有控制器的脚本
 * Created by PhpStorm.
 * User: shengsheng
 * Date: 2018/7/19
 * Time: 下午11:41
 */
$file = getcwd()."/phpshow/loader.php";
include_once $file;
/*
 demo:
    $db = new \phpshow\lib\db();
    var_dump($db);
*/